# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='lastrun',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='remotepath',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='ssl',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
